//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


#include "Measurement.generated.h"
namespace measurement
{
void MeasureSorting(Performancing* perf, uint64_t seed, int numberOfIterations, size_t arraySize, int measureIteration)
{
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR Def", &networks::best::sortN<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR JXc", &networks::best::sortN<SortableRef_JumpXchg>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR 4Cm", &networks::best::sortN<SortableRef_FourCmovTemp>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR 4CS", &networks::best::sortN<SortableRef_FourCmovTemp_Split>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR 6Cm", &networks::best::sortN<SortableRef_SixCmovRegisterTemp>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR Cla", &networks::best::sortN<SortableRef_ClangVersion>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR CPr", &networks::best::sortN<SortableRef_ClangPredicate>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR Tie", &networks::best::sortN<SortableRef_Tie>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR QMa", &networks::best::sortN<SortableRef_QMark>);
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR Def");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR JXc");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR 4Cm");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR 4CS");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR 6Cm");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR Cla");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR CPr");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR Tie");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -N KR QMa");
	
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR Def", &networks::bosenelson::sortN<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR JXc", &networks::bosenelson::sortN<SortableRef_JumpXchg>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR 4Cm", &networks::bosenelson::sortN<SortableRef_FourCmovTemp>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR 4CS", &networks::bosenelson::sortN<SortableRef_FourCmovTemp_Split>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR 6Cm", &networks::bosenelson::sortN<SortableRef_SixCmovRegisterTemp>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR Cla", &networks::bosenelson::sortN<SortableRef_ClangVersion>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR CPr", &networks::bosenelson::sortN<SortableRef_ClangPredicate>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR Tie", &networks::bosenelson::sortN<SortableRef_Tie>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR QMa", &networks::bosenelson::sortN<SortableRef_QMark>);
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR Def");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR JXc");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR 4Cm");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR 4CS");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR 6Cm");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR Cla");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR CPr");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR Tie");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BNLoc -N KR QMa");
	
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR Def", &networks::bosenelsonparallel::sortN<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR JXc", &networks::bosenelsonparallel::sortN<SortableRef_JumpXchg>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR 4Cm", &networks::bosenelsonparallel::sortN<SortableRef_FourCmovTemp>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR 4CS", &networks::bosenelsonparallel::sortN<SortableRef_FourCmovTemp_Split>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR 6Cm", &networks::bosenelsonparallel::sortN<SortableRef_SixCmovRegisterTemp>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR Cla", &networks::bosenelsonparallel::sortN<SortableRef_ClangVersion>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR CPr", &networks::bosenelsonparallel::sortN<SortableRef_ClangPredicate>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR Tie", &networks::bosenelsonparallel::sortN<SortableRef_Tie>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR QMa", &networks::bosenelsonparallel::sortN<SortableRef_QMark>);
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR Def");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR JXc");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR 4Cm");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR 4CS");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR 6Cm");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR Cla");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR CPr");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR Tie");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BNPL  -N KR QMa");
	
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR Def", &networks::bosenelsonparameter::sortN<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR JXc", &networks::bosenelsonparameter::sortN<SortableRef_JumpXchg>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR 4Cm", &networks::bosenelsonparameter::sortN<SortableRef_FourCmovTemp>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR 4CS", &networks::bosenelsonparameter::sortN<SortableRef_FourCmovTemp_Split>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR 6Cm", &networks::bosenelsonparameter::sortN<SortableRef_SixCmovRegisterTemp>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR Cla", &networks::bosenelsonparameter::sortN<SortableRef_ClangVersion>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR CPr", &networks::bosenelsonparameter::sortN<SortableRef_ClangPredicate>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR Tie", &networks::bosenelsonparameter::sortN<SortableRef_Tie>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR QMa", &networks::bosenelsonparameter::sortN<SortableRef_QMark>);
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR Def");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR JXc");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR 4Cm");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR 4CS");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR 6Cm");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR Cla");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR CPr");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR Tie");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BNPM  -N KR QMa");
	
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "I       -N KR Def", &insertionsort::InsertionSort<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_StlVersion>(perf, numberOfIterations, arraySize, measureIteration, "I       -N KR STL", &insertionsort::InsertionSort<SortableRef_StlVersion>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_PointerOptimized>(perf, numberOfIterations, arraySize, measureIteration, "I       -N KR POp", &insertionsort::InsertionSort<SortableRef_PointerOptimized>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ArrayIndex_FirstCheck>(perf, numberOfIterations, arraySize, measureIteration, "I       -N KR AIF", &insertionsort::InsertionSort<SortableRef_ArrayIndex_FirstCheck>);
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "I       -N KR Def");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_StlVersion>(perf, numberOfIterations, arraySize, measureIteration, "I       -N KR STL");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_PointerOptimized>(perf, numberOfIterations, arraySize, measureIteration, "I       -N KR POp");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ArrayIndex_FirstCheck>(perf, numberOfIterations, arraySize, measureIteration, "I       -N KR AIF");
	
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR Def", &networks::bosenelsonrecursive::sortN<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR JXc", &networks::bosenelsonrecursive::sortN<SortableRef_JumpXchg>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR 4Cm", &networks::bosenelsonrecursive::sortN<SortableRef_FourCmovTemp>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR 4CS", &networks::bosenelsonrecursive::sortN<SortableRef_FourCmovTemp_Split>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR 6Cm", &networks::bosenelsonrecursive::sortN<SortableRef_SixCmovRegisterTemp>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR Cla", &networks::bosenelsonrecursive::sortN<SortableRef_ClangVersion>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR CPr", &networks::bosenelsonrecursive::sortN<SortableRef_ClangPredicate>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR Tie", &networks::bosenelsonrecursive::sortN<SortableRef_Tie>);
	randomisation::SetSeed(seed);
	measurement::Measure<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR QMa", &networks::bosenelsonrecursive::sortN<SortableRef_QMark>);
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR Def");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR JXc");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR 4Cm");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR 4CS");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR 6Cm");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR Cla");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR CPr");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR Tie");
	randomisation::SetSeed(seed);
	measurement::MeasureRandomGeneration<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BNRec -N KR QMa");
	
}
} // namespace measurement
