template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
template <typename TValueType> statin inline
