//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


#include "Measurement.generated.h"
namespace measurement
{
void MeasureSortingInRow(Performancing* perf, uint64_t seed, int numberOfIterations, size_t arraySize, int measureIteration)
{
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -I KR Def", &networks::sortNbest<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -I KR JXc", &networks::sortNbest<SortableRef_JumpXchg>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -I KR 4Cm", &networks::sortNbest<SortableRef_FourCmovTemp>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -I KR 4CS", &networks::sortNbest<SortableRef_FourCmovTemp_Split>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -I KR 6Cm", &networks::sortNbest<SortableRef_SixCmovRegisterTemp>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -I KR Cla", &networks::sortNbest<SortableRef_ClangVersion>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -I KR CPr", &networks::sortNbest<SortableRef_ClangPredicate>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -I KR Tie", &networks::sortNbest<SortableRef_Tie>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N Best  -I KR QMa", &networks::sortNbest<SortableRef_QMark>);
	
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeL -I KR Def", &networks::sortNbosenelson<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeL -I KR JXc", &networks::sortNbosenelson<SortableRef_JumpXchg>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeL -I KR 4Cm", &networks::sortNbosenelson<SortableRef_FourCmovTemp>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeL -I KR 4CS", &networks::sortNbosenelson<SortableRef_FourCmovTemp_Split>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeL -I KR 6Cm", &networks::sortNbosenelson<SortableRef_SixCmovRegisterTemp>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeL -I KR Cla", &networks::sortNbosenelson<SortableRef_ClangVersion>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeL -I KR CPr", &networks::sortNbosenelson<SortableRef_ClangPredicate>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeL -I KR Tie", &networks::sortNbosenelson<SortableRef_Tie>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeL -I KR QMa", &networks::sortNbosenelson<SortableRef_QMark>);
	
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeP -I KR Def", &networks::sortNbosenelsonparallel<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeP -I KR JXc", &networks::sortNbosenelsonparallel<SortableRef_JumpXchg>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeP -I KR 4Cm", &networks::sortNbosenelsonparallel<SortableRef_FourCmovTemp>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeP -I KR 4CS", &networks::sortNbosenelsonparallel<SortableRef_FourCmovTemp_Split>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeP -I KR 6Cm", &networks::sortNbosenelsonparallel<SortableRef_SixCmovRegisterTemp>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeP -I KR Cla", &networks::sortNbosenelsonparallel<SortableRef_ClangVersion>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeP -I KR CPr", &networks::sortNbosenelsonparallel<SortableRef_ClangPredicate>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeP -I KR Tie", &networks::sortNbosenelsonparallel<SortableRef_Tie>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeP -I KR QMa", &networks::sortNbosenelsonparallel<SortableRef_QMark>);
	
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeM -I KR Def", &networks::sortNbosenelsonparameter<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeM -I KR JXc", &networks::sortNbosenelsonparameter<SortableRef_JumpXchg>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeM -I KR 4Cm", &networks::sortNbosenelsonparameter<SortableRef_FourCmovTemp>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeM -I KR 4CS", &networks::sortNbosenelsonparameter<SortableRef_FourCmovTemp_Split>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeM -I KR 6Cm", &networks::sortNbosenelsonparameter<SortableRef_SixCmovRegisterTemp>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeM -I KR Cla", &networks::sortNbosenelsonparameter<SortableRef_ClangVersion>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeM -I KR CPr", &networks::sortNbosenelsonparameter<SortableRef_ClangPredicate>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeM -I KR Tie", &networks::sortNbosenelsonparameter<SortableRef_Tie>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BoNeM -I KR QMa", &networks::sortNbosenelsonparameter<SortableRef_QMark>);
	
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "N BatcP -I KR Def", &networks::sortNbatcher<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "N BatcP -I KR JXc", &networks::sortNbatcher<SortableRef_JumpXchg>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BatcP -I KR 4Cm", &networks::sortNbatcher<SortableRef_FourCmovTemp>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "N BatcP -I KR 4CS", &networks::sortNbatcher<SortableRef_FourCmovTemp_Split>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "N BatcP -I KR 6Cm", &networks::sortNbatcher<SortableRef_SixCmovRegisterTemp>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "N BatcP -I KR Cla", &networks::sortNbatcher<SortableRef_ClangVersion>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ClangPredicate>(perf, numberOfIterations, arraySize, measureIteration, "N BatcP -I KR CPr", &networks::sortNbatcher<SortableRef_ClangPredicate>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_Tie>(perf, numberOfIterations, arraySize, measureIteration, "N BatcP -I KR Tie", &networks::sortNbatcher<SortableRef_Tie>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_QMark>(perf, numberOfIterations, arraySize, measureIteration, "N BatcP -I KR QMa", &networks::sortNbatcher<SortableRef_QMark>);
	
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "I       -I KR Def", &insertionsort::InsertionSort<SortableRef>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_StlVersion>(perf, numberOfIterations, arraySize, measureIteration, "I       -I KR STL", &insertionsort::InsertionSort<SortableRef_StlVersion>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_PointerOptimized>(perf, numberOfIterations, arraySize, measureIteration, "I       -I KR POp", &insertionsort::InsertionSort<SortableRef_PointerOptimized>);
	randomisation::SetSeed(seed);
	measurement::MeasureInRow<SortableRef_ArrayIndex_FirstCheck>(perf, numberOfIterations, arraySize, measureIteration, "I       -I KR AIF", &insertionsort::InsertionSort<SortableRef_ArrayIndex_FirstCheck>);
	
}
} // namespace measurement
