



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated from a T4 template
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


#ifndef MEASUREMENT_GENERATED_H
#define MEASUREMENT_GENERATED_H

#include "Sortable.generated.h"
#include "Performancing.h"
#include "EnvironmentInfo.h"
#include "Measure.h"
#include "BestNetworks.generated.h"
#include "BoseNelson.generated.h"
#include "InsertionSort.h"

namespace measurement
{

void MeasureSorting(Performancing* perf, int numberOfIterations, size_t arraySize, int measureIteration)
{
	measurement::Measure<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-Tuple", &networks::sortNbest<SortableRef>);
	measurement::Measure<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-JumpXchg", &networks::sortNbest<SortableRef_JumpXchg>);
	measurement::Measure<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-FourCmovTemp", &networks::sortNbest<SortableRef_FourCmovTemp>);
	measurement::Measure<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-FourCmovTemp-Split", &networks::sortNbest<SortableRef_FourCmovTemp_Split>);
	measurement::Measure<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-SixCmovRegisterTemp", &networks::sortNbest<SortableRef_SixCmovRegisterTemp>);
	measurement::Measure<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-ClangVersion", &networks::sortNbest<SortableRef_ClangVersion>);

	measurement::Measure<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-Tuple", &networks::sortNbosenelson<SortableRef>);
	measurement::Measure<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-JumpXchg", &networks::sortNbosenelson<SortableRef_JumpXchg>);
	measurement::Measure<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-FourCmovTemp", &networks::sortNbosenelson<SortableRef_FourCmovTemp>);
	measurement::Measure<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-FourCmovTemp-Split", &networks::sortNbosenelson<SortableRef_FourCmovTemp_Split>);
	measurement::Measure<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-SixCmovRegisterTemp", &networks::sortNbosenelson<SortableRef_SixCmovRegisterTemp>);
	measurement::Measure<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-ClangVersion", &networks::sortNbosenelson<SortableRef_ClangVersion>);

	measurement::Measure<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "Insertion Sort Key-Reference-Tuple", &insertionsort::InsertionSort<SortableRef>);
	measurement::Measure<SortableRef_StlVersion>(perf, numberOfIterations, arraySize, measureIteration, "Insertion Sort Key-Reference-StlVersion", &insertionsort::InsertionSort<SortableRef_StlVersion>);
	measurement::Measure<SortableRef_PointerOptimized>(perf, numberOfIterations, arraySize, measureIteration, "Insertion Sort Key-Reference-PointerOptimized", &insertionsort::InsertionSort<SortableRef_PointerOptimized>);
}

void MeasureRandomGenerationAndSortedChecking(Performancing* perf, int numberOfIterations, size_t arraySize, int measureIteration)
{
	measurement::MeasureRandomGeneration<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-Tuple");
	measurement::MeasureRandomGeneration<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-JumpXchg");
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-FourCmovTemp");
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-FourCmovTemp-Split");
	measurement::MeasureRandomGeneration<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-SixCmovRegisterTemp");
	measurement::MeasureRandomGeneration<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "Network Best Sort Key-Reference-ClangVersion");

	measurement::MeasureRandomGeneration<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-Tuple");
	measurement::MeasureRandomGeneration<SortableRef_JumpXchg>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-JumpXchg");
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-FourCmovTemp");
	measurement::MeasureRandomGeneration<SortableRef_FourCmovTemp_Split>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-FourCmovTemp-Split");
	measurement::MeasureRandomGeneration<SortableRef_SixCmovRegisterTemp>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-SixCmovRegisterTemp");
	measurement::MeasureRandomGeneration<SortableRef_ClangVersion>(perf, numberOfIterations, arraySize, measureIteration, "Network BoseNelson Sort Key-Reference-ClangVersion");

	measurement::MeasureRandomGeneration<SortableRef>(perf, numberOfIterations, arraySize, measureIteration, "Insertion Sort Key-Reference-Tuple");
	measurement::MeasureRandomGeneration<SortableRef_StlVersion>(perf, numberOfIterations, arraySize, measureIteration, "Insertion Sort Key-Reference-StlVersion");
	measurement::MeasureRandomGeneration<SortableRef_PointerOptimized>(perf, numberOfIterations, arraySize, measureIteration, "Insertion Sort Key-Reference-PointerOptimized");
}

}

#endif

