#include "networks/BestNetworks.generated.h"
#include "networks/BoseNelson.generated.h"
#include "networks/BoseNelsonParallel.generated.h"
#include "networks/BoseNelsonParameter.generated.h"
#include "networks/BoseNelsonRecursive.generated.h"
#include "networks/bose_nelson.h"
#include "networks/Batcher.generated.h"