//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef RANDOMISATION_GENERATED_H
#define RANDOMISATION_GENERATED_H

#include <stdexcept>
#include <cstddef>
#include "Randomisation.h"
#include "Sortable.generated.h"
namespace randomisation
{
template <typename ValueType>
void GenerateRandomArray(ValueType* arr, size_t arraySize)
{
	throw std::logic_error("randomisation::GenerateRandomArray => Not implemented for generic type");
}
template<>
void GenerateRandomArray<Sortable>(Sortable* arr, size_t arraySize);
template<>
void GenerateRandomArray<SortableRef>(SortableRef* arr, size_t arraySize);
} // namespace randomisation

#endif // RANDOMISATION_GENERATED_H
