//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef STRUCT_HELPERS_H
#define STRUCT_HELPERS_H

#define ArraySize 16
#include <inttypes.h>
#include "Sortable.generated.h"

template <typename TValueType>
static inline
uint64_t GetKey(TValueType& item)
{
	return 0;
}
template <typename TValueType>
static inline
uint64_t GetReference(TValueType& item)
{
	return 0;
}

template <>
inline
uint64_t GetKey(SortableRef& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(Sortable_JumpXchg& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(SortableRef_JumpXchg& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(Sortable_TwoCmovTemp& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(SortableRef_FourCmovTemp& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(SortableRef_FourCmovTemp_Split& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(Sortable_ThreeCmovRegisterTemp& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(SortableRef_SixCmovRegisterTemp& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(SortableRef_ClangVersion& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(SortableRef_Tie& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(SortableRef_QMark& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(SortableRef_StlVersion& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(SortableRef_PointerOptimized& item)
{
	return item.key;
}
template <>
inline
uint64_t GetKey(SortableRef_ArrayIndex_FirstCheck& item)
{
	return item.key;
}
template <>
inline
uint64_t GetReference(SortableRef& item)
{
	return item.reference;
}
template <>
inline
uint64_t GetReference(SortableRef_JumpXchg& item)
{
	return item.reference;
}
template <>
inline
uint64_t GetReference(SortableRef_FourCmovTemp& item)
{
	return item.reference;
}
template <>
inline
uint64_t GetReference(SortableRef_FourCmovTemp_Split& item)
{
	return item.reference;
}
template <>
inline
uint64_t GetReference(SortableRef_SixCmovRegisterTemp& item)
{
	return item.reference;
}
template <>
inline
uint64_t GetReference(SortableRef_ClangVersion& item)
{
	return item.reference;
}
template <>
inline
uint64_t GetReference(SortableRef_Tie& item)
{
	return item.reference;
}
template <>
inline
uint64_t GetReference(SortableRef_QMark& item)
{
	return item.reference;
}
template <>
inline
uint64_t GetReference(SortableRef_StlVersion& item)
{
	return item.reference;
}
template <>
inline
uint64_t GetReference(SortableRef_PointerOptimized& item)
{
	return item.reference;
}
template <>
inline
uint64_t GetReference(SortableRef_ArrayIndex_FirstCheck& item)
{
	return item.reference;
}

#endif // STRUCT_HELPERS_H
