//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#ifndef VERIFY_NETWORKS_H
#define VERIFY_NETWORKS_H

#include <inttypes.h>
#include <algorithm>
#include "ArrayHelpers.h"

namespace verification
{

bool VerifyNetwork(int size, void(*network)(int*,size_t))
{
	int* arr = (int*) malloc(sizeof(int) * size * 3);
	int* sorted = arr + size;
	int* toSort = arr + 2 * size;
	for (int index = 0; index < size; index += 1)
	{
		arr[index] = index;
	}
	CopyArray(arr, sorted, size);
	do
	{
		CopyArray(arr, toSort, size);
		network(toSort, size);
		if (!IsSameArray(sorted, toSort, size))
		{
			return false;
		}
	} while (std::next_permutation(arr, arr + size));

	return true;
}

}

#endif // VERIFY_NETWORKS_H
