

#include <vector>
#include <iostream>

#include "CodeGeneration.hpp"
#include "nlohmann/json.hpp"
#include "Network.hpp"
#include "GenerateBoseNelson.hpp"
#include "WriteNetwork.hpp"
#include "GenerateMeasurements.hpp"
#include "GenerateSortableStructs.hpp"
#include "GenerateStructHelpers.hpp"
#include "GenerateRandomisation.hpp"
#include "GenerateSampleSort.hpp"

using namespace codegeneration;

void GenerateSortableStructs()
{
    auto sortableStructsGen = new CodeGenerator("../../Sortable.generated.h");
    WriteSortableStructs(sortableStructsGen);
    delete sortableStructsGen;
}

void GenerateStructHelpers()
{
    auto structHelpersGen = new CodeGenerator("../../StructHelpers.generated.h");
    WriteStructHelpers(structHelpersGen);
    delete structHelpersGen;
}

void GenerateRandomisation()
{
    auto randomisationGen = new CodeGenerator("../../Randomisation.generated.h");
    WriteRandomisation(randomisationGen);
    delete randomisationGen;
}

void GenerateBoseNelsonNetworkJson()
{
    auto boseNelsonJsonGen = new CodeGenerator("../BoseNelsonNetworks.json");
    std::vector<nlohmann::json> boseNelsonNetworks;
    for (int arraySize = 2; arraySize <= 16; arraySize += 1)
    {
        boseNelsonNetworks.push_back(NetworkToJson(GenerateBoseNelsonNetwork(arraySize)));
    }
    nlohmann::json boseNelsonResult = nlohmann::json::array();
    for (auto network : boseNelsonNetworks)
    {
        boseNelsonResult.push_back(network);
    }
    boseNelsonJsonGen->WriteJson(boseNelsonResult);
    delete boseNelsonJsonGen;
}

void GenerateNetworks()
{
    auto boseNelsonGen = new CodeGenerator("../../BoseNelson.generated.h");
    WriteNetwork(boseNelsonGen, "BOSENELSON_GENERATED_H", "bosenelson", "../BoseNelsonNetworks.json");
    delete boseNelsonGen;

    auto bestNetworkGen = new CodeGenerator("../../BestNetworks.generated.h");
    WriteNetwork(bestNetworkGen, "BESTNETWORKS_GENERATED_H", "best", "../BestNetworks.json");
    delete bestNetworkGen;
}

void GenerateMeasurements()
{
    auto measurementGen = new CodeGenerator("../../Measurement.generated.h");
    GenerateMeasurementMethod(measurementGen);
    delete measurementGen;
}

void GenerateSampleSort()
{
    auto sampleSortGen = new CodeGenerator("../../SampleSort.generated.h");
    sampleSortGen->WriteLine(AutogeneratedPreamble);
    sampleSortGen->WriteHeaderPragma("SAMPLESORT_GENERATED_H", [=]{
        sampleSortGen->WriteIncludeBrackets("cstring");
        sampleSortGen->WriteNamespace("samplesort", [=]{
            for (int splits = 3; splits <= 3; splits += 1)
            {
                for (int oversample = 1; oversample * splits <= 16; oversample += 1)
                {
                    WriteFindSplitters(sampleSortGen, splits, oversample);
                    for (int blockSize = 1; blockSize <= 5; blockSize += 1)
                    {
                        WriteRegisterSampleSort(sampleSortGen, splits, oversample, blockSize);
                    }
                }
            }
        }, "");
    });
    
    delete sampleSortGen;
}

int main()
{
    GenerateSortableStructs();
    GenerateStructHelpers();
    GenerateRandomisation();
    GenerateBoseNelsonNetworkJson();
    GenerateNetworks();
    GenerateMeasurements();
    GenerateSampleSort();
}